services:
  frizzante:
    build:
      context: .
      target: frizzante_dev
    environment:
      APP_ENV: ${APP_ENV:-dev}
      DATABASE_URL: ${DATABASE_URL:-}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./:/app
      - /app/.gen