# Development environment override
services:
  frizzante:
    build:
      context: .
      target: frizzante_dev
    environment:
      APP_ENV: ${APP_ENV:-dev}
      # Enable/disable Delve debugger
      DELVE_ENABLED: ${DELVE_ENABLED:-false}
      DELVE_PORT: ${DELVE_PORT:-2345}
    ports:
      # Debugging port
      - target: 2345
        published: ${DELVE_PORT:-2345}
        protocol: tcp
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true