services:
  frizzante:
    build:
      context: .
      target: frizzante_dev
    environment:
      DELVE_ENABLED: ${DELVE_ENABLED:-false}
      DELVE_PORT: ${DELVE_PORT:-2345}
    ports:
      # Debugging port
      - target: 2345
        published: ${DELVE_PORT:-2345}
        protocol: tcp