services:
  frizzante:
    build:
      context: .
      target: frizzante_start
    container_name: frizzante-start
    environment:
      DEV: ${DEV:-}
      DATABASE_URL: ${DATABASE_URL:-}
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./:/frizzante
      - /frizzante/.gen